/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RestaurantRouteImport } from './routes/$restaurant'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as RestaurantIndexRouteImport } from './routes/$restaurant.index'
import { Route as RestaurantBranchRouteImport } from './routes/$restaurant.$branch'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedKitchenRouteImport } from './routes/_authenticated/kitchen'
import { Route as AuthenticatedLiveRouteImport } from './routes/_authenticated/live'
import { Route as AuthenticatedOwnerRouteImport } from './routes/_authenticated/owner'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteFeaturesRouteImport } from './routes/_site.features'
import { Route as SitePricingRouteImport } from './routes/_site.pricing'
import { Route as BusinessSplatRouteImport } from './routes/business.$'
import { Route as OrderOrderIdRouteImport } from './routes/order.$orderId'
import { Route as ProductProductIdRouteImport } from './routes/product.$productId'
import { Route as AuthenticatedAdminClientsClientIdRouteImport } from './routes/_authenticated/admin_.clients.$clientId'
import { Route as ApiPublicBrandLogoSplatRouteImport } from './routes/api/public/brand-logo.$'

const RestaurantRoute = RestaurantRouteImport.update({
  id: '/$restaurant',
  path: '/$restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantIndexRoute = RestaurantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RestaurantRoute,
} as any)
const RestaurantBranchRoute = RestaurantBranchRouteImport.update({
  id: '/$branch',
  path: '/$branch',
  getParentRoute: () => RestaurantRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKitchenRoute = AuthenticatedKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLiveRoute = AuthenticatedLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOwnerRoute = AuthenticatedOwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFeaturesRoute = SiteFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => SiteRoute,
} as any)
const SitePricingRoute = SitePricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => SiteRoute,
} as any)
const BusinessSplatRoute = BusinessSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => BusinessRoute,
} as any)
const OrderOrderIdRoute = OrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminClientsClientIdRoute =
  AuthenticatedAdminClientsClientIdRouteImport.update({
    id: '/admin_/clients/$clientId',
    path: '/admin/clients/$clientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicBrandLogoSplatRoute = ApiPublicBrandLogoSplatRouteImport.update({
  id: '/api/public/brand-logo/$',
  path: '/api/public/brand-logo/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/$restaurant': typeof RestaurantRouteWithChildren
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/business': typeof BusinessRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/$restaurant/$branch': typeof RestaurantBranchRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/kitchen': typeof AuthenticatedKitchenRoute
  '/live': typeof AuthenticatedLiveRoute
  '/owner': typeof AuthenticatedOwnerRoute
  '/contact': typeof SiteContactRoute
  '/features': typeof SiteFeaturesRoute
  '/pricing': typeof SitePricingRoute
  '/business/$': typeof BusinessSplatRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/$restaurant/': typeof RestaurantIndexRoute
  '/admin/clients/$clientId': typeof AuthenticatedAdminClientsClientIdRoute
  '/api/public/brand-logo/$': typeof ApiPublicBrandLogoSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof SiteIndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/business': typeof BusinessRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/$restaurant/$branch': typeof RestaurantBranchRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/kitchen': typeof AuthenticatedKitchenRoute
  '/live': typeof AuthenticatedLiveRoute
  '/owner': typeof AuthenticatedOwnerRoute
  '/contact': typeof SiteContactRoute
  '/features': typeof SiteFeaturesRoute
  '/pricing': typeof SitePricingRoute
  '/business/$': typeof BusinessSplatRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/$restaurant': typeof RestaurantIndexRoute
  '/admin/clients/$clientId': typeof AuthenticatedAdminClientsClientIdRoute
  '/api/public/brand-logo/$': typeof ApiPublicBrandLogoSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$restaurant': typeof RestaurantRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/business': typeof BusinessRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/$restaurant/$branch': typeof RestaurantBranchRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/kitchen': typeof AuthenticatedKitchenRoute
  '/_authenticated/live': typeof AuthenticatedLiveRoute
  '/_authenticated/owner': typeof AuthenticatedOwnerRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/features': typeof SiteFeaturesRoute
  '/_site/pricing': typeof SitePricingRoute
  '/business/$': typeof BusinessSplatRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/$restaurant/': typeof RestaurantIndexRoute
  '/_site/': typeof SiteIndexRoute
  '/_authenticated/admin_/clients/$clientId': typeof AuthenticatedAdminClientsClientIdRoute
  '/api/public/brand-logo/$': typeof ApiPublicBrandLogoSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$restaurant'
    | '/app'
    | '/auth'
    | '/business'
    | '/cart'
    | '/checkout'
    | '/menu'
    | '/orders'
    | '/$restaurant/$branch'
    | '/admin'
    | '/kitchen'
    | '/live'
    | '/owner'
    | '/contact'
    | '/features'
    | '/pricing'
    | '/business/$'
    | '/order/$orderId'
    | '/product/$productId'
    | '/$restaurant/'
    | '/admin/clients/$clientId'
    | '/api/public/brand-logo/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/business'
    | '/cart'
    | '/checkout'
    | '/menu'
    | '/orders'
    | '/$restaurant/$branch'
    | '/admin'
    | '/kitchen'
    | '/live'
    | '/owner'
    | '/contact'
    | '/features'
    | '/pricing'
    | '/business/$'
    | '/order/$orderId'
    | '/product/$productId'
    | '/$restaurant'
    | '/admin/clients/$clientId'
    | '/api/public/brand-logo/$'
  id:
    | '__root__'
    | '/_authenticated'
    | '/$restaurant'
    | '/_site'
    | '/app'
    | '/auth'
    | '/business'
    | '/cart'
    | '/checkout'
    | '/menu'
    | '/orders'
    | '/$restaurant/$branch'
    | '/_authenticated/admin'
    | '/_authenticated/kitchen'
    | '/_authenticated/live'
    | '/_authenticated/owner'
    | '/_site/contact'
    | '/_site/features'
    | '/_site/pricing'
    | '/business/$'
    | '/order/$orderId'
    | '/product/$productId'
    | '/$restaurant/'
    | '/_site/'
    | '/_authenticated/admin_/clients/$clientId'
    | '/api/public/brand-logo/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  RestaurantRoute: typeof RestaurantRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRoute
  BusinessRoute: typeof BusinessRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  MenuRoute: typeof MenuRoute
  OrdersRoute: typeof OrdersRoute
  OrderOrderIdRoute: typeof OrderOrderIdRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
  ApiPublicBrandLogoSplatRoute: typeof ApiPublicBrandLogoSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$restaurant': {
      id: '/$restaurant'
      path: '/$restaurant'
      fullPath: '/$restaurant'
      preLoaderRoute: typeof RestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$restaurant/': {
      id: '/$restaurant/'
      path: '/'
      fullPath: '/$restaurant/'
      preLoaderRoute: typeof RestaurantIndexRouteImport
      parentRoute: typeof RestaurantRoute
    }
    '/$restaurant/$branch': {
      id: '/$restaurant/$branch'
      path: '/$branch'
      fullPath: '/$restaurant/$branch'
      preLoaderRoute: typeof RestaurantBranchRouteImport
      parentRoute: typeof RestaurantRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kitchen': {
      id: '/_authenticated/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof AuthenticatedKitchenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live': {
      id: '/_authenticated/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof AuthenticatedLiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner': {
      id: '/_authenticated/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof AuthenticatedOwnerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/features': {
      id: '/_site/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof SiteFeaturesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/pricing': {
      id: '/_site/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof SitePricingRouteImport
      parentRoute: typeof SiteRoute
    }
    '/business/$': {
      id: '/business/$'
      path: '/$'
      fullPath: '/business/$'
      preLoaderRoute: typeof BusinessSplatRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/order/$orderId': {
      id: '/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/order/$orderId'
      preLoaderRoute: typeof OrderOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin_/clients/$clientId': {
      id: '/_authenticated/admin_/clients/$clientId'
      path: '/admin/clients/$clientId'
      fullPath: '/admin/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedAdminClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/brand-logo/$': {
      id: '/api/public/brand-logo/$'
      path: '/api/public/brand-logo/$'
      fullPath: '/api/public/brand-logo/$'
      preLoaderRoute: typeof ApiPublicBrandLogoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedKitchenRoute: typeof AuthenticatedKitchenRoute
  AuthenticatedLiveRoute: typeof AuthenticatedLiveRoute
  AuthenticatedOwnerRoute: typeof AuthenticatedOwnerRoute
  AuthenticatedAdminClientsClientIdRoute: typeof AuthenticatedAdminClientsClientIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedKitchenRoute: AuthenticatedKitchenRoute,
  AuthenticatedLiveRoute: AuthenticatedLiveRoute,
  AuthenticatedOwnerRoute: AuthenticatedOwnerRoute,
  AuthenticatedAdminClientsClientIdRoute:
    AuthenticatedAdminClientsClientIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface RestaurantRouteChildren {
  RestaurantBranchRoute: typeof RestaurantBranchRoute
  RestaurantIndexRoute: typeof RestaurantIndexRoute
}

const RestaurantRouteChildren: RestaurantRouteChildren = {
  RestaurantBranchRoute: RestaurantBranchRoute,
  RestaurantIndexRoute: RestaurantIndexRoute,
}

const RestaurantRouteWithChildren = RestaurantRoute._addFileChildren(
  RestaurantRouteChildren,
)

interface SiteRouteChildren {
  SiteContactRoute: typeof SiteContactRoute
  SiteFeaturesRoute: typeof SiteFeaturesRoute
  SitePricingRoute: typeof SitePricingRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteContactRoute: SiteContactRoute,
  SiteFeaturesRoute: SiteFeaturesRoute,
  SitePricingRoute: SitePricingRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface BusinessRouteChildren {
  BusinessSplatRoute: typeof BusinessSplatRoute
}

const BusinessRouteChildren: BusinessRouteChildren = {
  BusinessSplatRoute: BusinessSplatRoute,
}

const BusinessRouteWithChildren = BusinessRoute._addFileChildren(
  BusinessRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  RestaurantRoute: RestaurantRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
  AppRoute: AppRoute,
  AuthRoute: AuthRoute,
  BusinessRoute: BusinessRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  MenuRoute: MenuRoute,
  OrdersRoute: OrdersRoute,
  OrderOrderIdRoute: OrderOrderIdRoute,
  ProductProductIdRoute: ProductProductIdRoute,
  ApiPublicBrandLogoSplatRoute: ApiPublicBrandLogoSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
